kind: Service
apiVersion: v1
metadata:
  name: free5gc-webui-svc
spec:
  selector:
    app: free5gc-webui
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 31111
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-webui-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-webui
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-webui
    spec:
      containers:
      - name: free5gc-webui
        command: ["/bin/bash", "-c"]
        args: ["go run webconsole/server.go"]
        image: free5gmano/free5gc-control-plane:stage3.0.4
        volumeMounts:
        - name: webuicfg
          mountPath: /go/src/free5gc/config/webuicfg.conf
          subPath: webuicfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: webuicfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: webuicfg.conf
            path: webuicfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
